language: go
install:
  - go get github.com/bmizerany/assert
  - go get github.com/bitly/go-hostpool
  - go get github.com/bitly/go-simplejson
script:
  - pushd $TRAVIS_BUILD_DIR
  - ./test.sh
  - popd
notifications:
  email: false
